### PR TITLE
Add new style to staging project view

### PR DESCRIPTION
**Pull request by krauselukas**

### CODE REVIEW

**Comment by coolo** [comment]
Looks good from the diff of it - but could you attach a screenshot?

**Comment by krauselukas** [comment]
screenshot from 2017-11-23 12 59 23

**Comment by krauselukas** [comment]
@coolo Thought about adding a collapsing list for the missing reviews, like:
- repo-checker:
                         foo
                         bar
                         ....
- opensuse-review-team:
                         ....

**Comment by krauselukas** [comment]
@coolo But i will make this part of another PR. I will remove the WIP

**Pull request merged**
