### PR TITLE
Add entry for packages in state new to infobox in staging view

### PR DESCRIPTION
**Pull request by krauselukas**
Related to: https://github.com/openSUSE/obs_factory/issues/89

screenshot from 2018-01-22 18 14 52

### CODE REVIEW

**Comment by jberry-suse** [comment]
That list will commonly be over a hundred in length. As such it likely should be indicated in a better manor.

**Comment by krauselukas** [comment]
@jberry-suse Currently it will be shortend with the "N more". Not sure if that was your concern or more like "for now" its fine :) Where would you like to see this? It's still in progress, this was just the first implementation, just to have it. Suggestions are more then welcome.

**Comment by krauselukas** [comment]
@jberry-suse One idea is to make an collapsable list out of it or to create an link out of the "N more" which brings you to another view with the full list.

**Comment by coolo** [comment]
I had the same concern as @jberry-suse, but I think for SLE release managers it's mostly interesting that there are some.

**Comment by nilxam** [comment]
btw we see there is the package listed twice in the list.

**Comment by krauselukas** [comment]
@nilxam all packages twice? can't see at the moment, list is empty. but i will have a look

**Comment by nilxam** [comment]
sorry, no, not all package listed twice. but since it just can show the limited amount requests in the view, the issue might not easy to reproduce.

**Comment by krauselukas** [comment]
I will try to investigate this behavior :)

**Comment by jberry-suse** [comment]
If anything it likely makes sense to just link the heading or "more" to https://build.opensuse.org/project/requests/openSUSE:Leap:15.0 filter to `new` (assuming that can be specified as get argument or something). If not then likely want to add that capability to OBS or forget about this. :)

**Comment by jberry-suse** [comment]
It appears `state=new` works.

**Comment by jberry-suse** [comment]
If you decide to do so, could link the _Ignored_ header to the file in dashboard contain from which the list is sourced. The _Backlog_ can be linked to the relatively new group request pages (https://build.opensuse.org/group/show/factory-staging). If you can find a way to filter that on target project (perhaps using search if nothing better) that would be best.

**Comment by krauselukas** [comment]
@jberry-suse sounds good!

**Pull request merged**
