### PR TITLE
RFC:Add external api to OBS

### PR DESCRIPTION
**Pull request by k0da**
Optionally use external OBS api for real time data for debugging purposes

Signed-off-by: Dinar Valeev dvaleev@suse.com

### CODE REVIEW

**Comment by ancorgs** [comment]
My code smell detector tells me that all those `if OBS_CONFIG[...` should be encapsulated somewhere and not spread all over the code, maybe even using the strategy pattern as we already do with the distributions

**Comment by k0da** [comment]
updated

**Comment by coolo** [comment]
it still duplicates a lot, so having a strategy object that handles all the required actions and then is either  implemented by DBStrategy and APIStrategy, the code would be more straight forward

**Comment by lnussel** [comment]
quite old, should we close it?

**Comment by jberry-suse** [comment]
Would it be feasible to run an entire front-end against public OBS instance or redirect dashboard specific queries using a proxy with some rules?

**Comment by coolo** [comment]
https://github.com/openSUSE/open-build-service/pull/5140 -> the dashboard moves into obs

**Pull request closed without merging**
